/**
 * Represents an employee entity in the transport management system.
 * Used as the data contract between the Angular frontend and the REST API.
 */
export interface Employee {

  /** Unique identifier for the employee, generated by the database */
  id_employee: number;

  /** Full name of the employee, stored as a single field in the database */
  name: string;

  /** Last name of the employee, used only in the frontend form (not sent to the API) */
  lastName: string;

  /** Monthly salary of the employee */
  salary: number;

  /** Role assigned to the employee in the system (e.g. `ADMIN` | `CHOUFER`) */
  role: string;

  /** Username used to authenticate the employee in the system */
  username: string;

  /** Hashed password stored in the `oauth_users` table (only used on registration) */
  password: string;

  /** Total number of trips completed by the employee. Optional field */
  tripsCompleted?: number;
}