export interface Trip {
  /** Primary key; maps to `id_trip SERIAL PRIMARY KEY`. */
  id_trip: number;
  /** FK referencing the vehicle used for this trip. */
  id_transport: number;
  /** FK referencing the driver (employee) who completed this trip. */
  id_employee: number;
  /** FK referencing the route taken. */
  id_route: number;
  /** Revenue generated by this trip. */
  income: number;
  /** Fuel expense incurred during this trip. */
  fuelcost: number;
  /** Execution date; arrives as an ISO 8601 string from the SQL layer. */
  date: string;
}

export interface Route {
  /** Primary key; maps to `id_route SERIAL PRIMARY KEY`. */
  id_route: number;
  /** City or location where the route starts. */
  origin: string;
  /** City or location where the route ends. */
  destine: string;
  /** Total route length in kilometers. */
  distance: number;
}
